"""메시지 입력

Revision ID: 5b10db2b11de
Revises: 
Create Date: 2026-04-10 14:28:48.723928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b10db2b11de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('detection_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('is_simulation', sa.Boolean(), nullable=False),
    sa.Column('video_origin', sa.String(length=50), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('feedback', sa.Boolean(), nullable=True),
    sa.Column('resolved_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plate_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=50), nullable=False),
    sa.Column('ground_truth', sa.String(length=50), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('is_fixed', sa.Boolean(), nullable=True),
    sa.Column('img_path', sa.String(length=255), nullable=True),
    sa.Column('video_filename', sa.String(length=255), nullable=True),
    sa.Column('operator_name', sa.String(length=50), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operator_name'], ['users.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fire_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('fire_severity', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['detection_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manual_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['detection_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plate_preprocess_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('preprocess_method', sa.String(length=50), nullable=False),
    sa.Column('corrected_text', sa.String(length=50), nullable=False),
    sa.Column('ground_truth', sa.String(length=50), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('img_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['plate_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reverse_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('vehicle_info', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['detection_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reverse_results')
    op.drop_table('plate_preprocess_results')
    op.drop_table('manual_results')
    op.drop_table('fire_results')
    op.drop_table('plate_results')
    op.drop_table('detection_results')
    op.drop_table('users')
    # ### end Alembic commands ###
