"""Initial migration

Revision ID: e40956ec51d4
Revises: 
Create Date: 2026-04-09 15:23:38.459578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40956ec51d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plate_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=50), nullable=False),
    sa.Column('ground_truth', sa.String(length=50), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('is_fixed', sa.Boolean(), nullable=True),
    sa.Column('img_path', sa.String(length=255), nullable=True),
    sa.Column('video_filename', sa.String(length=255), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plate_preprocess_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('preprocess_method', sa.String(length=50), nullable=False),
    sa.Column('corrected_text', sa.String(length=50), nullable=False),
    sa.Column('ground_truth', sa.String(length=50), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('img_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['plate_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plate_preprocess_results')
    op.drop_table('plate_results')
    # ### end Alembic commands ###
